# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ryan/Desktop/oj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ryan/Desktop/oj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ryan/Desktop/oj/CMakeFiles /Users/ryan/Desktop/oj//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ryan/Desktop/oj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aPlusB.out

# Build rule for target.
aPlusB.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aPlusB.out
.PHONY : aPlusB.out

# fast build rule for target.
aPlusB.out/fast:
	$(MAKE) $(MAKESILENT) -f 0-intro/CMakeFiles/aPlusB.out.dir/build.make 0-intro/CMakeFiles/aPlusB.out.dir/build
.PHONY : aPlusB.out/fast

#=============================================================================
# Target rules for targets named hello.out

# Build rule for target.
hello.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello.out
.PHONY : hello.out

# fast build rule for target.
hello.out/fast:
	$(MAKE) $(MAKESILENT) -f 0-intro/CMakeFiles/hello.out.dir/build.make 0-intro/CMakeFiles/hello.out.dir/build
.PHONY : hello.out/fast

#=============================================================================
# Target rules for targets named guessNumber.out

# Build rule for target.
guessNumber.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 guessNumber.out
.PHONY : guessNumber.out

# fast build rule for target.
guessNumber.out/fast:
	$(MAKE) $(MAKESILENT) -f 0-intro/CMakeFiles/guessNumber.out.dir/build.make 0-intro/CMakeFiles/guessNumber.out.dir/build
.PHONY : guessNumber.out/fast

#=============================================================================
# Target rules for targets named mol.out

# Build rule for target.
mol.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mol.out
.PHONY : mol.out

# fast build rule for target.
mol.out/fast:
	$(MAKE) $(MAKESILENT) -f 1-types-io/CMakeFiles/mol.out.dir/build.make 1-types-io/CMakeFiles/mol.out.dir/build
.PHONY : mol.out/fast

#=============================================================================
# Target rules for targets named sphere.out

# Build rule for target.
sphere.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sphere.out
.PHONY : sphere.out

# fast build rule for target.
sphere.out/fast:
	$(MAKE) $(MAKESILENT) -f 1-types-io/CMakeFiles/sphere.out.dir/build.make 1-types-io/CMakeFiles/sphere.out.dir/build
.PHONY : sphere.out/fast

#=============================================================================
# Target rules for targets named circle.out

# Build rule for target.
circle.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 circle.out
.PHONY : circle.out

# fast build rule for target.
circle.out/fast:
	$(MAKE) $(MAKESILENT) -f 1-types-io/CMakeFiles/circle.out.dir/build.make 1-types-io/CMakeFiles/circle.out.dir/build
.PHONY : circle.out/fast

#=============================================================================
# Target rules for targets named pi.out

# Build rule for target.
pi.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pi.out
.PHONY : pi.out

# fast build rule for target.
pi.out/fast:
	$(MAKE) $(MAKESILENT) -f 1-types-io/hw/CMakeFiles/pi.out.dir/build.make 1-types-io/hw/CMakeFiles/pi.out.dir/build
.PHONY : pi.out/fast

#=============================================================================
# Target rules for targets named ob-evo.out

# Build rule for target.
ob-evo.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ob-evo.out
.PHONY : ob-evo.out

# fast build rule for target.
ob-evo.out/fast:
	$(MAKE) $(MAKESILENT) -f 2-if-for-array/CMakeFiles/ob-evo.out.dir/build.make 2-if-for-array/CMakeFiles/ob-evo.out.dir/build
.PHONY : ob-evo.out/fast

#=============================================================================
# Target rules for targets named single.out

# Build rule for target.
single.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 single.out
.PHONY : single.out

# fast build rule for target.
single.out/fast:
	$(MAKE) $(MAKESILENT) -f 2-if-for-array/CMakeFiles/single.out.dir/build.make 2-if-for-array/CMakeFiles/single.out.dir/build
.PHONY : single.out/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... aPlusB.out"
	@echo "... circle.out"
	@echo "... guessNumber.out"
	@echo "... hello.out"
	@echo "... mol.out"
	@echo "... ob-evo.out"
	@echo "... pi.out"
	@echo "... single.out"
	@echo "... sphere.out"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

